#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : pytest-cache
Version  : 1.0
Release  : 5
URL      : https://files.pythonhosted.org/packages/d1/15/082fd0428aab33d2bafa014f3beb241830427ba803a8912a5aaeaf3a5663/pytest-cache-1.0.tar.gz
Source0  : https://files.pythonhosted.org/packages/d1/15/082fd0428aab33d2bafa014f3beb241830427ba803a8912a5aaeaf3a5663/pytest-cache-1.0.tar.gz
Summary  : pytest plugin with mechanisms for caching across test runs
Group    : Development/Tools
License  : MIT
Requires: pytest-cache-license = %{version}-%{release}
Requires: pytest-cache-python = %{version}-%{release}
Requires: pytest-cache-python3 = %{version}-%{release}
Requires: execnet
Requires: pytest
BuildRequires : buildreq-distutils3
BuildRequires : execnet
BuildRequires : pluggy
BuildRequires : py-python
BuildRequires : pytest
BuildRequires : tox
BuildRequires : virtualenv

%description
=====================================================
        
        Usage
        ---------

%package license
Summary: license components for the pytest-cache package.
Group: Default

%description license
license components for the pytest-cache package.


%package python
Summary: python components for the pytest-cache package.
Group: Default
Requires: pytest-cache-python3 = %{version}-%{release}

%description python
python components for the pytest-cache package.


%package python3
Summary: python3 components for the pytest-cache package.
Group: Default
Requires: python3-core
Provides: pypi(pytest_cache)
Requires: pypi(execnet)
Requires: pypi(pytest)

%description python3
python3 components for the pytest-cache package.


%prep
%setup -q -n pytest-cache-1.0
cd %{_builddir}/pytest-cache-1.0

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1583529336
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
export CFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=4 "
export FCFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=4 "
export FFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=4 "
export CXXFLAGS="$CXXFLAGS -O3 -ffat-lto-objects -flto=4 "
export MAKEFLAGS=%{?_smp_mflags}
python3 setup.py build

%install
export MAKEFLAGS=%{?_smp_mflags}
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/pytest-cache
cp %{_builddir}/pytest-cache-1.0/LICENSE %{buildroot}/usr/share/package-licenses/pytest-cache/cf3eaf29116a37a7d9ba773e776104c067c8e5fc
python3 -tt setup.py build  install --root=%{buildroot}
echo ----[ mark ]----
cat %{buildroot}/usr/lib/python3*/site-packages/*/requires.txt || :
echo ----[ mark ]----

%files
%defattr(-,root,root,-)

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/pytest-cache/cf3eaf29116a37a7d9ba773e776104c067c8e5fc

%files python
%defattr(-,root,root,-)

%files python3
%defattr(-,root,root,-)
/usr/lib/python3*/*
